FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app
EXPOSE 80 

# Copy csproj and restore as distinct layers
COPY *.sln ./
COPY ./SignUp.Entities/*.csproj ./SignUp.Entities/
COPY ./SignUp.Web/*.csproj ./SignUp.Web/
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish SignUp.Web/*.csproj -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/SignUp.Web/out .
ENTRYPOINT ["dotnet", "SignUp.Web.dll"]