version: '3'

services:
  signup.web:
    image: signup.web
    build:
      context: .
      dockerfile: Dockerfile-Web
    ports:
       - "3300:80"
    networks:
       - signup-network
    depends_on:
       - signup.rabbit

  signup.mysql:
    image: signup.mysql
    build:
      context: ./SignUp.MySql
      dockerfile: Dockerfile-MySql
    volumes:
       - /c/Users/Usuario/Documents/MySqlData:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 'signuppass'
       MYSQL_DATABASE: 'SignUp'
       MYSQL_USER: 'web'
       MYSQL_PASSWORD: 'somepass'
    ports:
       - "3306:3306"
    networks:
       - signup-network

  signup.rabbit:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "8080:15672"
    hostname: signup.rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - /c/Users/Usuario/Documents/RabbitmqData:/var/lib/rabbitmq/mnesia
    networks:
       - signup-network

  signup.consumer.mysql:
    image: signup.consumer.sql
    build:
      context: .
      dockerfile: Dockerfile-Consumer-MySql
    ports:
       - "3301:80"
    networks:
       - signup-network
    depends_on:
       - signup.rabbit

  signup.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - signup-network
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  signup.consumer.es:
    image: signup.consumer.es
    build:
      context: .
      dockerfile: Dockerfile-Consumer-Es
    ports:
       - "3302:80"
    networks:
       - signup-network
    depends_on:
       - signup.rabbit
       - signup.elasticsearch

  signup.kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://signup.elasticsearch:9200
    networks:
       - signup-network
    depends_on:
       - signup.elasticsearch
    volumes:
       - kibana:/usr/share/kibana/data

volumes:
  elasticsearch:
  kibana:

networks:
  signup-network:
    driver: bridge